// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DiscoverReplyMessage_PeerAddress;
@class FindAckMessage_AeqAddress;
@class FindAckMessage_AimAddress;
@class FindAckMessage_Result;
@class FindMessage_AimAddress;
@class FindMessage_ReqAddress;
@class Transaction_AimAddress;
@class Transaction_Inputs;
@class Transaction_Inputs_IssueInput;
@class Transaction_Inputs_TradeInput;
@class Transaction_Inputs_TradeInput_Outpoint;
@class Transaction_Inputs_TradeInput_Outpoint_Hash;
@class Transaction_Outputs;
@class Transaction_ReqAddress;
@class Transaction_UnlockScripts;
@class Transaction_UnlockScripts_Outpoint;
@class Transaction_UnlockScripts_Outpoint_Hash;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Transaction_Inputs_InputType

typedef GPB_ENUM(Transaction_Inputs_InputType) {
  Transaction_Inputs_InputType_IssueType = 0,
  Transaction_Inputs_InputType_TradeType = 1,
};

GPBEnumDescriptor *Transaction_Inputs_InputType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Transaction_Inputs_InputType_IsValidValue(int32_t value);

#pragma mark - PbmessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PbmessageRoot : GPBRootObject
@end

#pragma mark - VersionMessage

typedef GPB_ENUM(VersionMessage_FieldNumber) {
  VersionMessage_FieldNumber_Timestamp = 1,
  VersionMessage_FieldNumber_Minimum = 2,
  VersionMessage_FieldNumber_MessageId = 3,
  VersionMessage_FieldNumber_ReplyId = 4,
  VersionMessage_FieldNumber_Version = 5,
  VersionMessage_FieldNumber_Services = 6,
  VersionMessage_FieldNumber_SubVer = 7,
  VersionMessage_FieldNumber_Id_p = 8,
  VersionMessage_FieldNumber_SessionId = 9,
  VersionMessage_FieldNumber_Opcode = 10,
};

@interface VersionMessage : GPBMessage

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t minimum;

@property(nonatomic, readwrite) BOOL hasMinimum;
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;
/** Test to see if @c replyId has been set. */
@property(nonatomic, readwrite) BOOL hasReplyId;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) BOOL hasVersion;
@property(nonatomic, readwrite) int64_t services;

@property(nonatomic, readwrite) BOOL hasServices;
@property(nonatomic, readwrite, copy, null_resettable) NSString *subVer;
/** Test to see if @c subVer has been set. */
@property(nonatomic, readwrite) BOOL hasSubVer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *opcode;
/** Test to see if @c opcode has been set. */
@property(nonatomic, readwrite) BOOL hasOpcode;

@end

#pragma mark - IMMessage

typedef GPB_ENUM(IMMessage_FieldNumber) {
  IMMessage_FieldNumber_Timestamp = 1,
  IMMessage_FieldNumber_Minimum = 2,
  IMMessage_FieldNumber_MessageId = 3,
  IMMessage_FieldNumber_ReplyId = 4,
  IMMessage_FieldNumber_Version = 5,
  IMMessage_FieldNumber_Services = 6,
  IMMessage_FieldNumber_SubVer = 7,
  IMMessage_FieldNumber_Id_p = 8,
  IMMessage_FieldNumber_Imjson = 9,
};

@interface IMMessage : GPBMessage

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t minimum;

@property(nonatomic, readwrite) BOOL hasMinimum;
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;
/** Test to see if @c replyId has been set. */
@property(nonatomic, readwrite) BOOL hasReplyId;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) BOOL hasVersion;
@property(nonatomic, readwrite) int64_t services;

@property(nonatomic, readwrite) BOOL hasServices;
@property(nonatomic, readwrite, copy, null_resettable) NSString *subVer;
/** Test to see if @c subVer has been set. */
@property(nonatomic, readwrite) BOOL hasSubVer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imjson;
/** Test to see if @c imjson has been set. */
@property(nonatomic, readwrite) BOOL hasImjson;

@end

#pragma mark - DiscoverMessage

typedef GPB_ENUM(DiscoverMessage_FieldNumber) {
  DiscoverMessage_FieldNumber_Timestamp = 1,
  DiscoverMessage_FieldNumber_Minimum = 2,
  DiscoverMessage_FieldNumber_MessageId = 3,
  DiscoverMessage_FieldNumber_ReplyId = 4,
};

@interface DiscoverMessage : GPBMessage

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t minimum;

@property(nonatomic, readwrite) BOOL hasMinimum;
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;
/** Test to see if @c replyId has been set. */
@property(nonatomic, readwrite) BOOL hasReplyId;

@end

#pragma mark - DiscoverReplyMessage

typedef GPB_ENUM(DiscoverReplyMessage_FieldNumber) {
  DiscoverReplyMessage_FieldNumber_Timestamp = 1,
  DiscoverReplyMessage_FieldNumber_Minimum = 2,
  DiscoverReplyMessage_FieldNumber_MessageId = 3,
  DiscoverReplyMessage_FieldNumber_ReplyId = 4,
  DiscoverReplyMessage_FieldNumber_PeerAddressArray = 5,
};

@interface DiscoverReplyMessage : GPBMessage

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t minimum;

@property(nonatomic, readwrite) BOOL hasMinimum;
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;
/** Test to see if @c replyId has been set. */
@property(nonatomic, readwrite) BOOL hasReplyId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DiscoverReplyMessage_PeerAddress*> *peerAddressArray;
/** The number of items in @c peerAddressArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger peerAddressArray_Count;

@end

#pragma mark - DiscoverReplyMessage_PeerAddress

typedef GPB_ENUM(DiscoverReplyMessage_PeerAddress_FieldNumber) {
  DiscoverReplyMessage_PeerAddress_FieldNumber_Address = 1,
  DiscoverReplyMessage_PeerAddress_FieldNumber_Services = 2,
  DiscoverReplyMessage_PeerAddress_FieldNumber_Id_p = 3,
  DiscoverReplyMessage_PeerAddress_FieldNumber_SessionId = 4,
};

@interface DiscoverReplyMessage_PeerAddress : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@property(nonatomic, readwrite) int64_t services;

@property(nonatomic, readwrite) BOOL hasServices;
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;
/** Test to see if @c id_p has been set. */
@property(nonatomic, readwrite) BOOL hasId_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;
/** Test to see if @c sessionId has been set. */
@property(nonatomic, readwrite) BOOL hasSessionId;

@end

#pragma mark - PingMessage

typedef GPB_ENUM(PingMessage_FieldNumber) {
  PingMessage_FieldNumber_Timestamp = 1,
  PingMessage_FieldNumber_Minimum = 2,
  PingMessage_FieldNumber_MessageId = 3,
  PingMessage_FieldNumber_ReplyId = 4,
  PingMessage_FieldNumber_Nonce = 5,
};

@interface PingMessage : GPBMessage

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t minimum;

@property(nonatomic, readwrite) BOOL hasMinimum;
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;
/** Test to see if @c replyId has been set. */
@property(nonatomic, readwrite) BOOL hasReplyId;

@property(nonatomic, readwrite) int64_t nonce;

@property(nonatomic, readwrite) BOOL hasNonce;
@end

#pragma mark - PongMessage

typedef GPB_ENUM(PongMessage_FieldNumber) {
  PongMessage_FieldNumber_Timestamp = 1,
  PongMessage_FieldNumber_Minimum = 2,
  PongMessage_FieldNumber_MessageId = 3,
  PongMessage_FieldNumber_ReplyId = 4,
  PongMessage_FieldNumber_Nonce = 5,
};

@interface PongMessage : GPBMessage

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t minimum;

@property(nonatomic, readwrite) BOOL hasMinimum;
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;
/** Test to see if @c replyId has been set. */
@property(nonatomic, readwrite) BOOL hasReplyId;

@property(nonatomic, readwrite) int64_t nonce;

@property(nonatomic, readwrite) BOOL hasNonce;
@end

#pragma mark - FindMessage

typedef GPB_ENUM(FindMessage_FieldNumber) {
  FindMessage_FieldNumber_Timestamp = 1,
  FindMessage_FieldNumber_Minimum = 2,
  FindMessage_FieldNumber_MessageId = 3,
  FindMessage_FieldNumber_ReplyId = 4,
  FindMessage_FieldNumber_ReqAddress = 5,
  FindMessage_FieldNumber_AimAddress = 6,
  FindMessage_FieldNumber_ReqId = 7,
  FindMessage_FieldNumber_AimId = 8,
  FindMessage_FieldNumber_ResourceType = 9,
  FindMessage_FieldNumber_Condition = 10,
};

@interface FindMessage : GPBMessage

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t minimum;

@property(nonatomic, readwrite) BOOL hasMinimum;
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;
/** Test to see if @c replyId has been set. */
@property(nonatomic, readwrite) BOOL hasReplyId;

@property(nonatomic, readwrite, strong, null_resettable) FindMessage_ReqAddress *reqAddress;
/** Test to see if @c reqAddress has been set. */
@property(nonatomic, readwrite) BOOL hasReqAddress;

@property(nonatomic, readwrite, strong, null_resettable) FindMessage_AimAddress *aimAddress;
/** Test to see if @c aimAddress has been set. */
@property(nonatomic, readwrite) BOOL hasAimAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reqId;
/** Test to see if @c reqId has been set. */
@property(nonatomic, readwrite) BOOL hasReqId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *aimId;
/** Test to see if @c aimId has been set. */
@property(nonatomic, readwrite) BOOL hasAimId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resourceType;
/** Test to see if @c resourceType has been set. */
@property(nonatomic, readwrite) BOOL hasResourceType;

@property(nonatomic, readwrite, copy, null_resettable) NSData *condition;
/** Test to see if @c condition has been set. */
@property(nonatomic, readwrite) BOOL hasCondition;

@end

#pragma mark - FindMessage_ReqAddress

typedef GPB_ENUM(FindMessage_ReqAddress_FieldNumber) {
  FindMessage_ReqAddress_FieldNumber_Address = 1,
};

@interface FindMessage_ReqAddress : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - FindMessage_AimAddress

typedef GPB_ENUM(FindMessage_AimAddress_FieldNumber) {
  FindMessage_AimAddress_FieldNumber_Address = 1,
};

@interface FindMessage_AimAddress : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - FindAckMessage

typedef GPB_ENUM(FindAckMessage_FieldNumber) {
  FindAckMessage_FieldNumber_Timestamp = 1,
  FindAckMessage_FieldNumber_Minimum = 2,
  FindAckMessage_FieldNumber_MessageId = 3,
  FindAckMessage_FieldNumber_ReplyId = 4,
  FindAckMessage_FieldNumber_AeqAddress = 5,
  FindAckMessage_FieldNumber_AimAddress = 6,
  FindAckMessage_FieldNumber_ReqId = 7,
  FindAckMessage_FieldNumber_AimId = 8,
  FindAckMessage_FieldNumber_Result = 9,
};

@interface FindAckMessage : GPBMessage

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t minimum;

@property(nonatomic, readwrite) BOOL hasMinimum;
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;
/** Test to see if @c replyId has been set. */
@property(nonatomic, readwrite) BOOL hasReplyId;

@property(nonatomic, readwrite, strong, null_resettable) FindAckMessage_AeqAddress *aeqAddress;
/** Test to see if @c aeqAddress has been set. */
@property(nonatomic, readwrite) BOOL hasAeqAddress;

@property(nonatomic, readwrite, strong, null_resettable) FindAckMessage_AimAddress *aimAddress;
/** Test to see if @c aimAddress has been set. */
@property(nonatomic, readwrite) BOOL hasAimAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reqId;
/** Test to see if @c reqId has been set. */
@property(nonatomic, readwrite) BOOL hasReqId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *aimId;
/** Test to see if @c aimId has been set. */
@property(nonatomic, readwrite) BOOL hasAimId;

@property(nonatomic, readwrite, strong, null_resettable) FindAckMessage_Result *result;
/** Test to see if @c result has been set. */
@property(nonatomic, readwrite) BOOL hasResult;

@end

#pragma mark - FindAckMessage_AeqAddress

typedef GPB_ENUM(FindAckMessage_AeqAddress_FieldNumber) {
  FindAckMessage_AeqAddress_FieldNumber_Address = 1,
};

@interface FindAckMessage_AeqAddress : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - FindAckMessage_AimAddress

typedef GPB_ENUM(FindAckMessage_AimAddress_FieldNumber) {
  FindAckMessage_AimAddress_FieldNumber_Address = 1,
};

@interface FindAckMessage_AimAddress : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - FindAckMessage_Result

typedef GPB_ENUM(FindAckMessage_Result_FieldNumber) {
  FindAckMessage_Result_FieldNumber_Data_p = 1,
};

@interface FindAckMessage_Result : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - Transaction

typedef GPB_ENUM(Transaction_FieldNumber) {
  Transaction_FieldNumber_Timestamp = 1,
  Transaction_FieldNumber_Minimum = 2,
  Transaction_FieldNumber_MessageId = 3,
  Transaction_FieldNumber_ReplyId = 4,
  Transaction_FieldNumber_ReqAddress = 5,
  Transaction_FieldNumber_AimAddress = 6,
  Transaction_FieldNumber_ReqId = 7,
  Transaction_FieldNumber_AimId = 8,
  Transaction_FieldNumber_InputsArray = 9,
  Transaction_FieldNumber_OutputsArray = 10,
  Transaction_FieldNumber_UnlockScriptsArray = 11,
  Transaction_FieldNumber_Version = 12,
  Transaction_FieldNumber_UpdatedAt = 13,
};

@interface Transaction : GPBMessage

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite) int32_t minimum;

@property(nonatomic, readwrite) BOOL hasMinimum;
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *replyId;
/** Test to see if @c replyId has been set. */
@property(nonatomic, readwrite) BOOL hasReplyId;

@property(nonatomic, readwrite, strong, null_resettable) Transaction_ReqAddress *reqAddress;
/** Test to see if @c reqAddress has been set. */
@property(nonatomic, readwrite) BOOL hasReqAddress;

@property(nonatomic, readwrite, strong, null_resettable) Transaction_AimAddress *aimAddress;
/** Test to see if @c aimAddress has been set. */
@property(nonatomic, readwrite) BOOL hasAimAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reqId;
/** Test to see if @c reqId has been set. */
@property(nonatomic, readwrite) BOOL hasReqId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *aimId;
/** Test to see if @c aimId has been set. */
@property(nonatomic, readwrite) BOOL hasAimId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Transaction_Inputs*> *inputsArray;
/** The number of items in @c inputsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger inputsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Transaction_Outputs*> *outputsArray;
/** The number of items in @c outputsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger outputsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Transaction_UnlockScripts*> *unlockScriptsArray;
/** The number of items in @c unlockScriptsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger unlockScriptsArray_Count;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) BOOL hasVersion;
@property(nonatomic, readwrite) uint64_t updatedAt;

@property(nonatomic, readwrite) BOOL hasUpdatedAt;
@end

#pragma mark - Transaction_ReqAddress

typedef GPB_ENUM(Transaction_ReqAddress_FieldNumber) {
  Transaction_ReqAddress_FieldNumber_Address = 1,
};

@interface Transaction_ReqAddress : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - Transaction_AimAddress

typedef GPB_ENUM(Transaction_AimAddress_FieldNumber) {
  Transaction_AimAddress_FieldNumber_Address = 1,
};

@interface Transaction_AimAddress : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - Transaction_Inputs

typedef GPB_ENUM(Transaction_Inputs_FieldNumber) {
  Transaction_Inputs_FieldNumber_Sequence = 1,
  Transaction_Inputs_FieldNumber_InputType = 2,
  Transaction_Inputs_FieldNumber_TradeInput = 3,
  Transaction_Inputs_FieldNumber_IssueInput = 4,
};

@interface Transaction_Inputs : GPBMessage

@property(nonatomic, readwrite) int64_t sequence;

@property(nonatomic, readwrite) BOOL hasSequence;
@property(nonatomic, readwrite) Transaction_Inputs_InputType inputType;

@property(nonatomic, readwrite) BOOL hasInputType;
@property(nonatomic, readwrite, strong, null_resettable) Transaction_Inputs_TradeInput *tradeInput;
/** Test to see if @c tradeInput has been set. */
@property(nonatomic, readwrite) BOOL hasTradeInput;

@property(nonatomic, readwrite, strong, null_resettable) Transaction_Inputs_IssueInput *issueInput;
/** Test to see if @c issueInput has been set. */
@property(nonatomic, readwrite) BOOL hasIssueInput;

@end

#pragma mark - Transaction_Inputs_TradeInput

typedef GPB_ENUM(Transaction_Inputs_TradeInput_FieldNumber) {
  Transaction_Inputs_TradeInput_FieldNumber_Outpoint = 1,
};

@interface Transaction_Inputs_TradeInput : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Transaction_Inputs_TradeInput_Outpoint *outpoint;
/** Test to see if @c outpoint has been set. */
@property(nonatomic, readwrite) BOOL hasOutpoint;

@end

#pragma mark - Transaction_Inputs_TradeInput_Outpoint

typedef GPB_ENUM(Transaction_Inputs_TradeInput_Outpoint_FieldNumber) {
  Transaction_Inputs_TradeInput_Outpoint_FieldNumber_Hash_p = 1,
  Transaction_Inputs_TradeInput_Outpoint_FieldNumber_Index = 2,
  Transaction_Inputs_TradeInput_Outpoint_FieldNumber_IsSpend = 3,
};

@interface Transaction_Inputs_TradeInput_Outpoint : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Transaction_Inputs_TradeInput_Outpoint_Hash *hash_p;
/** Test to see if @c hash_p has been set. */
@property(nonatomic, readwrite) BOOL hasHash_p;

@property(nonatomic, readwrite) int64_t index;

@property(nonatomic, readwrite) BOOL hasIndex;
@property(nonatomic, readwrite) BOOL isSpend;

@property(nonatomic, readwrite) BOOL hasIsSpend;
@end

#pragma mark - Transaction_Inputs_TradeInput_Outpoint_Hash

typedef GPB_ENUM(Transaction_Inputs_TradeInput_Outpoint_Hash_FieldNumber) {
  Transaction_Inputs_TradeInput_Outpoint_Hash_FieldNumber_Bytes = 1,
};

@interface Transaction_Inputs_TradeInput_Outpoint_Hash : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *bytes;
/** Test to see if @c bytes has been set. */
@property(nonatomic, readwrite) BOOL hasBytes;

@end

#pragma mark - Transaction_Inputs_IssueInput

typedef GPB_ENUM(Transaction_Inputs_IssueInput_FieldNumber) {
  Transaction_Inputs_IssueInput_FieldNumber_SourceType = 1,
  Transaction_Inputs_IssueInput_FieldNumber_Data_p = 2,
};

@interface Transaction_Inputs_IssueInput : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sourceType;
/** Test to see if @c sourceType has been set. */
@property(nonatomic, readwrite) BOOL hasSourceType;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - Transaction_Outputs

typedef GPB_ENUM(Transaction_Outputs_FieldNumber) {
  Transaction_Outputs_FieldNumber_ScriptBytes = 1,
  Transaction_Outputs_FieldNumber_Value = 2,
};

@interface Transaction_Outputs : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *scriptBytes;
/** Test to see if @c scriptBytes has been set. */
@property(nonatomic, readwrite) BOOL hasScriptBytes;

@property(nonatomic, readwrite, copy, null_resettable) NSData *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

#pragma mark - Transaction_UnlockScripts

typedef GPB_ENUM(Transaction_UnlockScripts_FieldNumber) {
  Transaction_UnlockScripts_FieldNumber_ScriptBytes = 1,
  Transaction_UnlockScripts_FieldNumber_Outpoint = 2,
  Transaction_UnlockScripts_FieldNumber_Sequence = 3,
};

@interface Transaction_UnlockScripts : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *scriptBytes;
/** Test to see if @c scriptBytes has been set. */
@property(nonatomic, readwrite) BOOL hasScriptBytes;

@property(nonatomic, readwrite, strong, null_resettable) Transaction_UnlockScripts_Outpoint *outpoint;
/** Test to see if @c outpoint has been set. */
@property(nonatomic, readwrite) BOOL hasOutpoint;

@property(nonatomic, readwrite) int64_t sequence;

@property(nonatomic, readwrite) BOOL hasSequence;
@end

#pragma mark - Transaction_UnlockScripts_Outpoint

typedef GPB_ENUM(Transaction_UnlockScripts_Outpoint_FieldNumber) {
  Transaction_UnlockScripts_Outpoint_FieldNumber_Hash_p = 1,
  Transaction_UnlockScripts_Outpoint_FieldNumber_Index = 2,
  Transaction_UnlockScripts_Outpoint_FieldNumber_IsSpend = 3,
};

@interface Transaction_UnlockScripts_Outpoint : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Transaction_UnlockScripts_Outpoint_Hash *hash_p;
/** Test to see if @c hash_p has been set. */
@property(nonatomic, readwrite) BOOL hasHash_p;

@property(nonatomic, readwrite) int64_t index;

@property(nonatomic, readwrite) BOOL hasIndex;
@property(nonatomic, readwrite) BOOL isSpend;

@property(nonatomic, readwrite) BOOL hasIsSpend;
@end

#pragma mark - Transaction_UnlockScripts_Outpoint_Hash

typedef GPB_ENUM(Transaction_UnlockScripts_Outpoint_Hash_FieldNumber) {
  Transaction_UnlockScripts_Outpoint_Hash_FieldNumber_Bytes = 1,
};

@interface Transaction_UnlockScripts_Outpoint_Hash : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *bytes;
/** Test to see if @c bytes has been set. */
@property(nonatomic, readwrite) BOOL hasBytes;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
